bitcoin api example fixes
polkaswitch/examples pull request #55
Opened 2024-04-12 22:56 UTC by heyOnuoha

## Changelog

- Examples: Polish and Make Bitcoin API Example responsive: FIXES DX-17

2024-04-13 15:03 UTC, chillvybz requested changes
Seems like the approve/allowance still missing, but after talking on slack Karina has asked to take it out of scope and save it for the pure-EVM example.

2024-04-13 15:03 UTC, chillvybz commented on README.md
>  - [swaps-api-nextjs](./examples/swaps-api-nextjs/README.md) - Cross-chain Swaps using the Swing API in Next.js
Is this link still valid?

2024-04-13 15:03 UTC, chillvybz commented on examples/swaps-api-nextjs-bitcoin/src/components/Swap.tsx
> +      transactionStatus?.status == "Transaction Failed"
It's not "Transaction Failed", I would check for IncompleteStatus

https://github.com/swing-xyz/crosschain-swap-api/blob/development/src/utils/txstatus.ts#L21-L26

Which is:
  SUBMITTED = 'Submitted',
  PENDING_SOURCE = 'Pending Source Chain',
  PENDING_DEST = 'Pending Destination Chain',
  NOT_SENT = 'Not Sent',

If it's one of these, I would keep polling.

2024-04-13 15:24 UTC, heyOnuoha commented on examples/swaps-api-nextjs-bitcoin/src/components/Swap.tsx
> +      transactionStatus?.status == "Transaction Failed"
So I'm polling as long as the Status is not "Completed" or if the transaction fails `before` it's even sent

```
export const getTransationStatus = async (
  statusParams: TransactionStatusParams,
): Promise<TransactionStatusAPIResponse> => {
  try {
    const response = await axios.get<TransactionStatusAPIResponse>(
      `${baseUrl}/transfer/status`,
      { params: { ...statusParams, projectId } },
    );

    if (response.status === 404) {
      return { status: "Not Found " };
    }
    return response.data;
  } catch (error) {
    console.error("Error fetching transaction status:", error);

    return { status: "Transaction Failed" };
  }
};
```

"Transaction Failed" is a custom status I return if the request fails and the API returns an error like say "Bad Request"

2024-04-13 18:57 UTC, chillvybz commented on examples/swaps-api-nextjs-bitcoin/src/components/Swap.tsx
> +      transactionStatus?.status == "Transaction Failed"
Okay sure but the status is not always going to be 'COMPLETED' for a given tx. It can have multiple end-states as initially stated.

And this custom "Transaction Failed" is an edge-case here because why would you send any list of params that returns "Bad Request". That would basically be a bug.

 Most of the time, it's going to return the raw response from the API.
 
 We want this example at least demonstrate the right way to implement /status endpoint.

2024-04-13 19:17 UTC, heyOnuoha commented on examples/swaps-api-nextjs-bitcoin/src/components/Swap.tsx
> +      transactionStatus?.status == "Transaction Failed"
Understood! I'll make changes around it

2024-04-14 01:04 UTC, chillvybz commented on examples/swaps-api-nextjs-bitcoin/README.md
> +  } else if (transactionStatus?.status == "Completed") {
You don't need the else if. it can just be ` } else {`

2024-04-14 05:43 UTC, heyOnuoha commented on examples/swaps-api-nextjs-bitcoin/README.md
> +  } else if (transactionStatus?.status == "Completed") {
Done!

2024-04-14 14:03 UTC, chillvybz approved these changes

2024-04-14 14:04 UTC, merged