add example: solana api example
polkaswitch/examples pull request #62
Opened 2024-05-16 23:45 UTC by heyOnuoha

2024-05-23 20:11 UTC, chillvybz requested changes

2024-05-23 20:11 UTC, chillvybz commented on examples/swaps-api-nextjs-solana/README.md
> +      contractCall: true,
why is contractCall true here? when it's false above?

2024-05-23 20:11 UTC, chillvybz commented on examples/swaps-api-nextjs-solana/README.md
> +## Sending a Token Approval Request for ERC20 Tokens (Optional)
Why is this "Optional"?

2024-05-23 20:11 UTC, chillvybz commented on examples/swaps-api-nextjs-solana/README.md
> +    if (transferParams.fromChain !== "solana") {
why are you checking if not solana? maybe add a comment why this is needed

2024-05-23 20:11 UTC, chillvybz commented on examples/swaps-api-nextjs-solana/README.md
> +try {
have you actually executed these steps yourself?

2024-05-23 20:11 UTC, chillvybz commented on examples/swaps-api-nextjs-solana/README.md
> +URL: [https://swap.prod.swing.xyz/v0/transfer/status](https://developers.swing.xyz/reference/api/cross-chain/6b61efd1b798a-transfer-status)
This is confusing since you are fetching `"/projects/{projectId}/transactions/{transactionId}"` but are linking to `https://swap.prod.swing.xyz/v0/transfer/status`. that needs explanation or fixing or improving.

2024-05-23 20:12 UTC, heyOnuoha commented on examples/swaps-api-nextjs-solana/README.md
> +try {
Yes, I have

2024-05-23 20:20 UTC, heyOnuoha commented on examples/swaps-api-nextjs-solana/README.md
> +## Sending a Token Approval Request for ERC20 Tokens (Optional)
It's an optional step in the transfer flow if the source token is not an ERC20 token.

2024-05-23 20:21 UTC, heyOnuoha commented on examples/swaps-api-nextjs-solana/README.md
> +      contractCall: true,
Ouch, that's a typo, will fix

2024-05-23 20:22 UTC, heyOnuoha commented on examples/swaps-api-nextjs-solana/README.md
> +URL: [https://swap.prod.swing.xyz/v0/transfer/status](https://developers.swing.xyz/reference/api/cross-chain/6b61efd1b798a-transfer-status)
Thanks for pointing that out, will fix that

2024-05-23 20:26 UTC, heyOnuoha commented on examples/swaps-api-nextjs-solana/README.md
> +    if (transferParams.fromChain !== "solana") {
I'm checking the source chain to know whether I'm executing a SOL transaction or an Ethereum transaction. I'll add a comment there

2024-05-27 16:58 UTC, chillvybz approved these changes

2024-05-27 17:00 UTC, merged